python HSTconstraints.py SIDM0.1
rm -fr component_finding_*
rm -fr DMmass_*
python HSTconstraints.py SIDM0.3
rm -fr component_finding_*
rm -fr DMmass_*
python HSTconstraints.py SIDM1
rm -fr component_finding_*
rm -fr DMmass_*
python HSTconstraints.py vdSIDM
rm -fr component_finding_*
rm -fr DMmass_*
python HSTconstraints.py CDM_hi
rm -fr component_finding_*
rm -fr DMmass_*
python HSTconstraints.py CDM_low
rm -fr component_finding_*
rm -fr DMmass_*
python HSTconstraints.py CDM
rm -fr component_finding_*
rm -fr DMmass_*
